### ISSUE TITLE
Problem downloading 5.6.30

### ISSUE THREAD

**Issue by bperkins62** [liip/php-osx#212]
Running: sudo curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6.30   (I also ran as root)
The script stops at "Did or could not download package: 5.6.30-frontenddev"

    $ sudo curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6.30
    Password:
    Detected OS X El Capitan 10.11. All ok.
    Get packager.tgz
    Unpack packager.tgz
    Please type in your password, as we want to install this into /usr/local
    Password:
    Start packager (may take some time)
    Password:
    downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/5.6.30-frontenddev-latest.dat
    downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/<?xml version="1.0" encoding="UTF-8"?>

    downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/5.6.30-frontenddev.tar.bz2
    downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/5.6.30-frontenddev.tar.gz
    downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/5.6.30-frontenddev.tgz
    Did or could not download package: 5.6.30-frontenddev

Attempts to access https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/ and https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/5.6.30/ directly show Access Denied in the XML response.

Any help would be appreciated.

**Comment by bperkins62** [comment]
On another machine I get a different error. In this case the packager.py fails:

	# curl -s https://php-osx.liip.ch/install.sh | bash -s 5.6.30
	Detected OS X Yosemite 10.10. All ok.
	Get packager.tgz
	Unpack packager.tgz
	Please type in your password, as we want to install this into /usr/local
	Start packager (may take some time)
	downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/5.6.30-frontenddev-latest.dat
	Traceback (most recent call last):
	  File "/usr/local/packager/packager.py", line 553, in <module>
	    c.run()
	  File "/usr/local/packager/packager.py", line 41, in run
	    cmd_obj.run(self, params, options)
	  File "/usr/local/packager/packager.py", line 146, in run
	    pkg = Package(param, registry)
	  File "/usr/local/packager/packager.py", line 183, in __init__
	    self.__fetch(name, registry)
	  File "/usr/local/packager/packager.py", line 358, in __fetch
	    filehandle = urllib.urlopen(baselatest)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, in urlopen
	    return opener.open(url)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
	    return getattr(self, name)(url)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 350, in open_http
	    h.endheaders(data)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
	    self._send_output(message_body)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
	    self.send(msg)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
	    self.connect()
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
	    self.timeout, self.source_address)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
	    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
	IOError: [Errno socket error] [Errno 8] nodename nor servname provided, or not known

**Comment by bperkins62** [comment]
Trying to install it manually, e.g.., $sudo /usr/local/packager/packager.py install 5.6.30-frontdenddev results in the original error where the end result is:

Did or could not download package: 5.6.30-frontenddev

**Comment by mflynn-lanl** [comment]
I tried debugging the python script to get a better idea of where it was failing. I noticed that it downloaded a .bz2 file to a temp directory but the tarfile python library was unable to open it. Also, urlopen for the .dat file had a 403 status code, so perhaps that's the origin of the error.

**Comment by chregu** [comment]
`curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6`
works fine for me, you can't tell it which exact version it should use, just to the major.minor versions

**Comment by bperkins62** [comment]
Thank you. That worked. I thought I'd tried that previously.
