### ISSUE TITLE
Installing PHP 7.1 fails

### ISSUE THREAD

**Issue by Frickey** [liip/php-osx#223]
I used the command provided, curl -s https://php-osx.liip.ch/install.sh | bash -s 7.1, but it failed.  Below is the output.  

=====================
Detected macOS Sierra 10.12. All ok.
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Password:
Start packager (may take some time) using /usr/bin/python2.7
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/7.1-10.10-frontenddev-latest.dat
Traceback (most recent call last):
  File "/usr/local/packager/packager.py", line 561, in <module>
    c.run()
  File "/usr/local/packager/packager.py", line 50, in run
    cmd_obj.run(self, params, options)
  File "/usr/local/packager/packager.py", line 155, in run
    pkg = Package(param, registry)
  File "/usr/local/packager/packager.py", line 192, in __init__
    self.__fetch(name, registry)
  File "/usr/local/packager/packager.py", line 367, in __fetch
    filehandle = urllib.urlopen(baselatest)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 60] Operation timed out
Finished.

**Comment by sitthykun** [comment]
Yes sure, that is the case i come raise with you.
I get stuck while it is curling

**Comment by bzjianfeng** [comment]
I have the same question

**Comment by stefanhirt** [comment]
I have the same issue here. Looks like it has to do with our proxy which requires authentication.

**Comment by tri-duong-vn** [comment]
I have the same issue with 10.13
