### ISSUE TITLE
What changes do I need to install behind a proxy?

### ISSUE THREAD

**Issue by codecowboy** [liip/php-osx#25]
sudo /usr/local/packager/packager.py install tools-frontenddev gives me:

downloading http://php-osx.liip.ch/install/tools-frontenddev-latest.dat
Traceback (most recent call last):
  File "/usr/local/packager/packager.py", line 553, in <module>
    c.run()
  File "/usr/local/packager/packager.py", line 41, in run
    cmd_obj.run(self, params, options)
  File "/usr/local/packager/packager.py", line 146, in run
    pkg = Package(param, registry)
  File "/usr/local/packager/packager.py", line 183, in **init**
    self.__fetch(name, registry)
  File "/usr/local/packager/packager.py", line 358, in __fetch
    filehandle = urllib.urlopen(baselatest)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib.py", line 203, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib.py", line 310, in open_http
    if proxy_bypass(realhost):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib.py", line 1555, in proxy_bypass
    return proxy_bypass_macosx_sysconf(host)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib.py", line 1425, in proxy_bypass_macosx_sysconf
    mask = int(m.group(2)[1:])
TypeError: 'NoneType' object is unsubscriptable

**Comment by emale999** [comment]
Environment variable is set and `curl -s https://php-osx.liip.ch/install.sh | bash -s 7.2` works (it downloads install.sh and executes it) but the python script has problems with our proxy:

`Detected macOS High Sierra 10.13. All ok.
Get packager.tgz

Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Start packager (may take some time) using /usr/bin/python2.7
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/7.2-10.10-frontenddev-latest.dat
Traceback (most recent call last):
  File "/usr/local/packager/packager.py", line 561, in <module>
    c.run()
  File "/usr/local/packager/packager.py", line 50, in run
    cmd_obj.run(self, params, options)
  File "/usr/local/packager/packager.py", line 155, in run
    pkg = Package(param, registry)
  File "/usr/local/packager/packager.py", line 192, in __init__
    self.__fetch(name, registry)
  File "/usr/local/packager/packager.py", line 367, in __fetch
    filehandle = urllib.urlopen(baselatest)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 357, in open_http
    'got a bad status line', None)
IOError: ('http protocol error', 0, 'got a bad status line', None)
Finished.`

Is there any way to do an offline-installation? Did download the archive 7.2-10.10-frontenddev-7.2.9-20180821-074958.tar.bz2 that python wanted to download and that contains all necessary files for updating but can't get packager.py to just take this already downloaded file instead of trying to download it.
